services:
  postgres:
    image: postgres:18-alpine
    container_name: universal-starter-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecret}
      - POSTGRES_DB=${POSTGRES_DB:-universal-starter}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: universal-starter-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-supersecret}
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_DATABASE=${REDIS_DATABASE:-0}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
