services:
  api:
    build:
      context: ..
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env

  workers:
    build:
      context: ..
      dockerfile: ./apps/workers/Dockerfile
    env_file:
      - ./apps/workers/.env

  frontend:
    build:
      context: ..
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./apps/frontend/.env
