version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env

  workers:
    build:
      context: ..
      dockerfile: ./apps/workers/Dockerfile
    env_file:
      - ./apps/workers/.env
