version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    volumes:
      - ../apps/api:/app/apps/api
      - ../packages:/app/packages
      - ../bun.lock:/app/bun.lock
      - ../package.json:/app/package.json
    depends_on:
      - db
      - redis

  workers:
    build:
      context: ..
      dockerfile: ./apps/workers/Dockerfile
    volumes:
      - ../apps/workers:/app/apps/workers
      - ../packages:/app/packages
      - ../bun.lock:/app/bun.lock
      - ../package.json:/app/package.json
    env_file:
      - ./apps/workers/.env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: universal_starter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
